# Generated by Django 4.1.5 on 2023-01-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmodel',
            old_name='urlandroid',
            new_name='android_link',
        ),
        migrations.RenameField(
            model_name='linkmodel',
            old_name='urlcombine',
            new_name='ios_link',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='urlios',
        ),
    ]
