# Generated by Django 4.1.5 on 2023-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0002_rename_urlandroid_linkmodel_android_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
