# Generated by Django 4.1.5 on 2023-01-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0004_linkmodel_created_at_linkmodel_fallback_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
