# Generated by Django 4.1.5 on 2023-01-31 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0005_linkmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 31, 15, 33, 10, 739457)),
        ),
    ]
