# Generated by Django 4.1.5 on 2023-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0006_alter_linkmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
