# Generated by Django 4.1.5 on 2023-01-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0008_pagevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
