# Generated by Django 4.1.5 on 2023-01-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0009_delete_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
