# Generated by Django 4.1.5 on 2023-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0010_linkvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkVisit',
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='appname',
            field=models.TextField(blank=True),
        ),
    ]
