# Generated by Django 4.1.5 on 2023-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0011_delete_linkvisit_linkmodel_appname'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='original_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
