# Generated by Django 4.1.5 on 2023-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0012_linkmodel_original_url_linkmodel_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='short_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
