# Generated by Django 4.1.5 on 2023-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0014_alter_linkmodel_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='short_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
