# Generated by Django 4.1.5 on 2023-02-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0015_alter_linkmodel_short_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='original_url',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='short_code',
        ),
    ]
