# Generated by Django 4.1.5 on 2023-02-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0016_remove_linkmodel_original_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
