# Generated by Django 4.1.5 on 2023-02-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelink', '0018_remove_linkmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
